const DESICION_CONST = {
  DESICION_EPIDEMIC_REQUEST: "DESICION_EPIDEMIC_REQUEST",
  DESICION_EPIDEMIC_SUCCESS: "DESICION_EPIDEMIC_SUCCESS",
  DESICION_EPIDEMIC_ERROR: "DESICION_EPIDEMIC_ERROR",

  DESICION_CATEGORY_REQUEST: "DESICION_CATEGORY_REQUEST",
  DESICION_CATEGORY_SUCCESS: "DESICION_CATEGORY_SUCCESS",
  DESICION_CATEGORY_ERROR: "DESICION_CATEGORY_ERROR",

  DESICION_INTERVENTIONS_REQUEST: "DESICION_INTERVENTIONS_REQUEST",
  DESICION_INTERVENTIONS_SUCCESS: "DESICION_INTERVENTIONS_SUCCESS",
  DESICION_INTERVENTIONS_ERROR: "DESICION_INTERVENTIONS_ERROR",
};
export default DESICION_CONST;
