const LOCATION_CONST = {
  LOCATION_REQUEST: "LOCATION_REQUEST",
  LOCATION_SUCCESS: "LOCATION_SUCCESS",
  LOCATION_ERROR: "LOCATION_ERROR",

  LOCATION_STATE_REQUEST: "LOCATION_STATE_REQUEST",
  LOCATION_STATE_SUCCESS: "LOCATION_STATE_SUCCESS",
  LOCATION_STATE_ERROR: "LOCATION_STATE_ERROR",

  LOCATION_SUB_REQUEST: "LOCATION_SUB_REQUEST",
  LOCATION_SUB_SUCCESS: "LOCATION_SUB_SUCCESS",
  LOCATION_SUB_ERROR: "LOCATION_SUB_ERROR",
};
export default LOCATION_CONST;
