const HOME_CONST = {
  HOME_BANNER_REQUEST: "HOME_BANNER_REQUEST",
  HOME_BANNER_SUCCESS: "HOME_BANNER_SUCCESS",
  HOME_BANNER_ERROR: "HOME_BANNER_ERROR",

  HOME_GENERAL_TOOLS_REQUEST: "HOME_GENERAL_TOOLS_REQUEST",
  HOME_GENERAL_TOOLS_SUCCESS: "HOME_GENERAL_TOOLS_SUCCESS",
  HOME_GENERAL_TOOLS_ERROR: "HOME_GENERAL_TOOLS_ERROR",
};

export default HOME_CONST;
