const DASHBOARD_CONST = {
  DASHBOARD_SOURCE_REQUEST: "DASHBOARD_SOURCE_REQUEST",
  DASHBOARD_SOURCE_SUCCESS: "DASHBOARD_SOURCE_SUCCESS",
  DASHBOARD_SOURCE_ERROR: "DASHBOARD_SOURCE_ERROR",

  ADD_MAP_REQUEST: "ADD_MAP_REQUEST",
  ADD_MAP_SUCCESS: "ADD_MAP_SUCCESS",
  ADD_MAP_ERROR: "ADD_MAP_ERROR",

  ADD_MAP1_REQUEST: "ADD_MAP1_REQUEST",
  ADD_MAP1_SUCCESS: "ADD_MAP1_SUCCESS",
  ADD_MAP1_ERROR: "ADD_MAP1_ERROR",

  GET_TIMESERIES_REQUEST: "GET_TIMESERIES_REQUEST",
  GET_TIMESERIES_SUCCESS: "GET_TIMESERIES_SUCCESS",
  GET_TIMESERIES_ERROR: "GET_TIMESERIES_ERROR",

  ADD_RVF_MAP_REQUEST: "ADD_RVF_MAP_REQUEST",
  ADD_RVF_MAP_SUCCESS: "ADD_RVF_MAP_SUCCESS",
  ADD_RVF_MAP_ERROR: "ADD_RVF_MAP_ERROR",

  GET_RVF_TIMESERIES_REQUEST: "GET_RVF_TIMESERIES_REQUEST",
  GET_RVF_TIMESERIES_SUCCESS: "GET_RVF_TIMESERIES_SUCCESS",
  GET_RVF_TIMESERIES_ERROR: "GET_RVF_TIMESERIES_ERROR",

  GET_GFS_NOVA_REQUEST: "GET_GFS_NOVA_REQUEST",
  GET_GFS_NOVA_SUCCESS: "GET_GFS_NOVA_SUCCESS",
  GET_GFS_NOVA_ERROR: "GET_GFS_NOVA_ERROR",

  MODEL_MAP_REQUEST: "MODEL_MAP_REQUEST",
  MODEL_MAP_SUCCESS: "MODEL_MAP_SUCCESS",
  MODEL_MAP_ERROR: "MODEL_MAP_ERROR",

  GET_GFS_NOVA_TEMPERATURE_REQUEST: "GET_GFS_NOVA_TEMPERATURE_REQUEST",
  GET_GFS_NOVA_TEMPERATURE_SUCCESS: "GET_GFS_NOVA_TEMPERATURE_SUCCESS",
  GET_GFS_NOVA_TEMPERATURE_ERROR: "GET_GFS_NOVA_TEMPERATURE_ERROR",
};
export default DASHBOARD_CONST;
