const BULLETIN_CONSTS = {
  ADD_BULLETIN_REQUEST: "ADD_BULLETIN_REQUEST",
  ADD_BULLETIN_SUCCESS: "ADD_BULLETIN_SUCCESS",
  ADD_BULLETIN_FAILED: "ADD_BULLETIN_FAILED",

  GET_BULLETIN_REQUEST: "GET_BULLETIN_REQUEST",
  GET_BULLETIN_SUCCESS: "GET_BULLETIN_SUCCESS",
  GET_BULLETIN_FAILED: "GET_BULLETIN_FAILED",

  SHARE_BULLETIN_REQUEST: "SHARE_BULLETIN_REQUEST",
  SHARE_BULLETIN_SUCCESS: "SHARE_BULLETIN_SUCCESS",
  SHARE_BULLETIN_FAILED: "SHARE_BULLETIN_FAILED",

  MAIL_LIST_REQUEST: "MAIL_LIST_REQUEST",
  MAIL_LIST_SUCCESS: "MAIL_LIST_SUCCESS",
  MAIL_LIST_FAILED: "MAIL_LIST_FAILED",
};

export default BULLETIN_CONSTS;
